### ISSUE TITLE
Optimization issue when I implement "main.py" with defaut parameters.

### ISSUE THREAD

**Issue by Usaywook** [Mgineer117/Meta-CPO#2] opened 2024-09-02 00:58 UTC
When I implement main.py with [default parameters ](https://github.com/Mgineer117/Meta-CPO/blob/main/utils/argument_parsing.py)in `SafetyCarStcircle` environment, I got the following error during training.
```
Please consider re-formulating your problem so that it is always solvable or increasing the number of solver iterations.
Traceback (most recent call last):
  File "$ProjectPath/Meta-CPO/algos/CPOMeta.py", line 485, in update
    (step,) = self.cpo_problem(g, max_kl, a, b)
  File "/home/ubuntu/anaconda3/envs/metaicl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/metaicl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/metaicl/lib/python3.10/site-packages/cvxpylayers/torch/cvxpylayer.py", line 153, in forward
    sol = f(*params)
  File "/home/ubuntu/anaconda3/envs/metaicl/lib/python3.10/site-packages/torch/autograd/function.py", line 553, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/ubuntu/anaconda3/envs/metaicl/lib/python3.10/site-packages/cvxpylayers/torch/cvxpylayer.py", line 275, in forward
    c, _, neg_A, b = compiler.apply_parameters(
  File "/home/ubuntu/anaconda3/envs/metaicl/lib/python3.10/site-packages/cvxpy/reductions/dcp2cone/cone_matrix_stuffing.py", line 191, in apply_parameters
    A, b = self.reduced_A.get_matrix_from_tensor(param_vec, with_offset=True)                                         
  File "/home/ubuntu/anaconda3/envs/metaicl/lib/python3.10/site-packages/cvxpy/reductions/utilities.py", line 167, in get_matrix_from_tensor
    return canonInterface.get_matrix_from_tensor(
  File "/home/ubuntu/anaconda3/envs/metaicl/lib/python3.10/site-packages/cvxpy/cvxcore/python/canonInterface.py", line 244, in get_matrix_from_tensor
    A_rows, A_cols = nonzero_csc_matrix(A)
  File "/home/ubuntu/anaconda3/envs/metaicl/lib/python3.10/site-packages/cvxpy/cvxcore/python/canonInterface.py", line 152, in nonzero_csc_matrix
    assert not np.isnan(A.data).any()
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "$ProjectPath/Meta-CPO/main.py", line 132, in <module>                                        
    main_loop()
  File "$ProjectPath/Meta-CPO/main.py", line 129, in main_loop                                       
    algo.train_CPOMeta(writer, save_info_obj)
  File "$ProjectPath/Meta-CPO/algos/CPOMeta.py", line 699, in train_CPOMeta
    meta_correction = self.update(memory.sample(), meta_update=True)
  File "$ProjectPath/Meta-CPO/algos/CPOMeta.py", line 489, in update
    (step,) = self.trpo_problem(a, max_kl)
  File "/home/ubuntu/anaconda3/envs/metaicl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/metaicl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/metaicl/lib/python3.10/site-packages/cvxpylayers/torch/cvxpylayer.py", line 153, in forward
    sol = f(*params)
  File "/home/ubuntu/anaconda3/envs/metaicl/lib/python3.10/site-packages/torch/autograd/function.py", line 553, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/ubuntu/anaconda3/envs/metaicl/lib/python3.10/site-packages/cvxpylayers/torch/cvxpylayer.py", line 296, in forward
    raise e
  File "/home/ubuntu/anaconda3/envs/metaicl/lib/python3.10/site-packages/cvxpylayers/torch/cvxpylayer.py", line 289, in forward
    xs, _, _, _, ctx.DT_batch = diffcp.solve_and_derivative_batch(
  File "/home/ubuntu/anaconda3/envs/metaicl/lib/python3.10/site-packages/diffcp/cone_program.py", line 80, in solve_and_derivative_batch
    x, y, s, D, DT = solve_and_derivative(As[i], bs[i], cs[i],
  File "/home/ubuntu/anaconda3/envs/metaicl/lib/python3.10/site-packages/diffcp/cone_program.py", line 216, in solve_and_derivative
    result = solve_and_derivative_internal(
  File "/home/ubuntu/anaconda3/envs/metaicl/lib/python3.10/site-packages/diffcp/cone_program.py", line 298, in solve_and_derivative_internal
    raise SolverError("Solver scs returned status %s" % status)
diffcp.cone_program.SolverError: Solver scs returned status unbounded (inaccurate - reached max_iters)
```

While solving the CPO problem using DPO in the main loop, the AssertionError happened, so it went to the exception line solving the TRPO problem, but the SolverError was raised.
Moreover, the learning curve shows that no learning is taking place at all.
![Screenshot from 2024-09-02 09-50-23](https://github.com/user-attachments/assets/789ef25c-fed5-435f-a344-87ca90248bbd)

The default parameters are not proper for SafetyCarStcircle environments. 
It seems that overly conservative behavior hinders task learning, as the cost decreases but the reward does not increase at all.

**How could I solve it?**

If you could provide some guidance on parameters for each environment, it would be a great help in utilizing the code in this paper.

**Comment by Mgineer117** [comment] 2024-09-02 01:28
Hi! I am sorry for the issue you encountered. 

First, I would like to admit that this is the problem I also had during this research. This is attributed to the instability of the DCO and gradient computing. However, I mitigated this issue **using careful learning rate selection and grad norm** to avoid gradient explosion. **I suggest that you want to lower the learning of the BFGS algorithm** (0.1 -> lower maybe 1e-3 or 1e-4) at CPOMeta line 399~400, which may alleviate the gradient instability issue. 

Second, the error **"Please consider re-formulating your problem so that it is always..."** is attributed to the insolvable CPO problem which naturally leads to solely decreasing cost value using TRPO. I should mention that in the README.

Third, I just reran the code with the default parameters and got the code working as shown in the image below:

![Screenshot from 2024-09-01 20-21-33](https://github.com/user-attachments/assets/3b7de7d6-00f9-4996-83e9-04bd9ffd732c)

Would you be able to check the code once more? Please feel free to shoot me an e-mail at minjae5@illinois.edu if you want any further discussion in this regard.

**Comment by Mgineer117** [comment] 2024-09-02 04:36
For rigorous analysis, I will leave my additional experiments with another parameter. Hope I can upload it by tomorrow!

**Comment by Mgineer117** [comment] 2024-09-02 21:45
Hi, and thanks for your patience. Although I was unable to replicate the exact divergence you encountered, I admit there is a gradient instability from your replication that **likely stems from improper learning rate selection when using BFGS (this is my fault sorry!! lr=0.1 seems to be high, though my previous experiments did fine with it).** 

To relieve gradient instability, I carefully added some following features:
**1. gradient clipping for critic network**
**2. lower learning rate for BFGS**
**3. higher batch size (4trj ->6trj) to enhance gradient estimation**

I also compared BFGS to the ADAM optimizer for the critic network updates, and **BFGS with gradient clipping and a lower learning rate proved to be both efficient and effective as image below.** Thus, I incorporated the option to use the ADAM optimizer, allowing flexibility in choosing the optimizer that best suits your needs. 

![Screenshot from 2024-09-02 15-57-15](https://github.com/user-attachments/assets/4282e5d4-558a-43a1-bfa6-2358a42bf263)
**where blue is BFGS and red is ADAM.** Sorry once again for the inconvenience and appreciate you brought the issue to me! Please do not hesitate for further assistant. Good luck for your research @Usaywook [😊](https://emojipedia.org/smiling-face-with-smiling-eyes)!

**Comment by Usaywook** [comment] 2024-09-02 23:56
Thank you for the detailed explanation of parameter selections.
After reflecting on the commits on Sep 2, 2024, I also experimented with the different learning rates using BFGS; 0.1, 0.01, 0.001, 0.0001.
The below figures show the results:
![Screenshot from 2024-09-03 08-18-24](https://github.com/user-attachments/assets/9f1494c5-35b9-4724-990d-b70ee14cba90)

Except for learning rate 1e-4, all faced the same optimization error as the first question corresponding to the optimization issue.

Although there was an optimization issue, fortunately, **I could see that the cost decreased and reward increased at learning rates such as 1e-2 and 1e-3. However, using the learning rate 1e-4 is so small that the improvement speed is too slow.**

Therefore, as you mentioned in the previous response, increasing the batch size and clipping the gradients with learning rate 1e-2 or le-3 would probably help with gradient exploding. 

To confirm the results that I think, I will reflect recent update and try again with learning rates of 1e-2 and le-3.

**Comment by Mgineer117** [comment] 2024-09-03 00:37
Thank you for confirming that. In my experience, **BFGS can be quite sensitive depending on the environment domain**, but, in some cases, it's generally more effective and leads to faster convergence compared to Adam. So, BFGS was more appealing since "Meta" framework is already computationally expensive, which is why I chose it initially. 

I also just saw **lr = 1e-3** worked fine **while 1e-4 worked poorly**. The optimization error you observed is the one I also had the issue with. **What I remember is that BFGS caused divergence in the critic network by exploding gradient.** Hopefully, gradient clipping prevents that.

Additionally, I'll be running deeper experiments overnight to compare the performance of Adam and BFGS in this regard. I'll update you with the results, likely tomorrow.

**Comment by Usaywook** [comment] 2024-09-03 06:37
After trying the experiment reflecting on recent updates regarding gradient clipping and increasing batch size, 
I still have confronted the divergence issue as follows:
![image](https://github.com/user-attachments/assets/86c71144-2aa7-4e95-ae7d-e088ba2172f5)

After reviewing the whole code, I knew there were some differences in implementing CPO unlike [referenced repository](https://github.com/SapanaChaudhary/PyTorch-CPO.git).

- First, it was to use "torch.optim.LBFGS" module instead of "scipy.optimize.fmin_l_bfgs_b" to regress the critics. Since the optimal step size is calculated internally through line search, the "scipy.optimize.fmin_l_bfgs_b" module is thought to be more efficient for implementing CPO, which is sensitive to changes in learning rate.

- Second, cvxpy module optimized the CPO objective and constraints without a backtracking line search for feasible cases. 
If cvxpy module is used, we could not regulate the learning rate for exceptional cases regarding safety bound and feasibility like the original CPO paper.

- Finally, I found another issue regarding DCO implementation.
After checking the code in [algo/CPOMeta.py](https://github.com/Mgineer117/Meta-CPO/blob/main/algos/CPOMeta.py) script, I have noticed that the projection step to seek the intersection of the safe set for each task is currently used. **How could the projection step be applied?**

It seems like a lot of work to control all three cases.

Is there any easy solution to reproduce the results of the Meta-CPO method?

**Comment by Mgineer117** [comment] 2024-09-03 11:30
Thank you for your valuable feedback. I've recently updated the code to incorporate the following changes:

**1. Line Search:** I've implemented line search within CPO-Meta to ensure convergence and improve optimization efficiency.
**2. Scipy BFGS:** I've reverted to using Scipy BFGS for the optimization step. Though I ran it with Scipy BFGS for experiments in the paper, I now remember changing to torch BFGS for code consistency in publishing code (was a bad decision). As you already mentioned, Scipy BFGS offers specific advantages in certain scenarios while I wasn't aware of such a significant difference.
**3. Projection:** I've added a projection step.

You're absolutely right about the potential limitations of using DCO for solving CPO. While DCO operate with a convexified objective function, it may not always yield the same solution as the original CPO as DCO iterates. However, CPO-Meta must use DCO to relax the differentiation bottleneck of MAML, and I expect the line search I added will mitigate the issue. 

I apologize for any inconvenience caused by the premature publication of the code since I was in the middle of havoc at that time. I am keeping my eye on the experiment if it works fine, but committing this new change in case you also want to look at it.

**Comment by Mgineer117** [comment] 2024-09-04 10:28
@Usaywook Hi! I’ve confirmed that the code works with the additional features. I recall that the meta-parameter update was quite sensitive, even with projection and line search, so I introduced a scaling factor of 1e-1 to the meta-update step to address this. I’ve committed the changes, and I hope they help! 

![Screenshot from 2024-09-04 05-27-01](https://github.com/user-attachments/assets/39b66e96-f38c-4611-a8e4-5ea9326e3a06)

The **blue-wise curves with scaler 1e-1** and **red-wise curves with 1e-2**. Again, thanks for bringing this to me, and  I apologize this kind of journey due to the premature code release.

**Comment by Usaywook** [comment] 2024-09-04 11:08
Thank you for reflecting my concern rigorously, I will try again, reflecting the latest commit.

**Comment by Mgineer117** [comment] 2024-09-08 16:26
I am closing this issue since the code works.

**Closed as completed by Mgineer117** 2024-09-08 16:26 UTC
Labels: bug, enhancement
